---
apiVersion: v1
kind: Pod
metadata:
  name: uor-framework
  labels:
    app: uor-framework
  annotations:
    io.kubernetes.cri-o.TTY/hugo: "false"
    io.podman.annotations.init/hugo: "FALSE"
    io.podman.annotations.label/hugo: disable
    io.podman.annotations.autoremove/hugo: "TRUE"
    io.podman.annotations.privileged/hugo: "FALSE"
    io.podman.annotations.publish-all/hugo: "FALSE"
    org.opencontainers.image.base.name/hugo: ghcr.io/uor-framework/hugo:latest
spec:
  containers:
  - image: ghcr.io/uor-framework/hugo:latest
    name: hugo
    ports:
    - containerPort: 1313
      hostPort: 1313
    securityContext:
      capabilitieskj:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /src
      name: uor-framework.github.io
  volumes:
  - name: uor-framework.github.io
    hostPath:
      type: Directory
      path: .
