name: github pages

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      -
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: .
          git-user: uor-framework
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
